name: tourmate
environment:
  sdk: '^3.8.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity_plus: ^7.0.0
  firebase_core: ^2.30.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  overlay_support: ^2.1.0
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^1.0.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  flutter_dotenv: ^5.1.0
  google_maps_webservice: ^0.0.19
  flutter_local_notifications: ^18.0.1
  # Use your local fixed plugin instead of pub.dev
  background_location:
    path: plugins/background_location-0.11.8
  permission_handler: ^11.3.0
  equatable: ^2.0.7
  http: ^0.13.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.7.10
  cloudinary_public: ^0.23.1
  logger: ^2.0.0
  cached_network_image: ^3.3.1
  universal_html: ^2.2.4
  mime: ^1.0.4
  intl: ^0.18.0
  collection: ^1.18.0
  url_launcher: ^6.2.5

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - .env